### ISSUE TITLE
Error: BoxSystemNotDetected

### ISSUE THREAD

**Issue by karasuhebi** [PokemonAutomation/ComputerControl#111] opened 2023-01-01 17:30 UTC
Version: 0.25.3
OS: Windows 10 Version 21H2
CPU: AMD Ryzen 5 5600X
Memory: 16 GB
GPU: NVIDIA GeForce GTX 1080 Ti

2023-01-01 12:10:09.472244 - [Console 0]: ConvertFrame: Count = 91, Mean = 5.98475ms, Stddev = 0.370873ms, Min = 5.475ms, Max = 7.07ms
2023-01-01 12:10:09.474554 - [Console 0]: Sending: pbf_press_button() - seqnum = 5582, button = 4( BUTTON_A ), hold_ticks = 60, release_ticks = 60
2023-01-01 12:10:10.434518 - [Console 0]: Swapped slots.
2023-01-01 12:10:10.434955 - [Console 0]: Unload party to column 1.
2023-01-01 12:10:10.434974 - [Console 0]: Move cursor to (PARTY row 1 col 0).
2023-01-01 12:10:19.482218 - [Console 0]: ConvertFrame: Count = 83, Mean = 6.13823ms, Stddev = 0.510266ms, Min = 5.579ms, Max = 8.736ms
2023-01-01 12:10:21.462005 - [Console 0]: Saving failed inference image to: ErrorDumps/20230101-121021461995-BoxSystemNotDetected.png
2023-01-01 12:10:21.603427 - [Console 0]: Scheduling Webhook Message... (queue = 1)
2023-01-01 12:10:21.603458 - [Console 0]: OperationFailedException: move_cursor(): Unable to detect box system.
2023-01-01 12:10:21.604471 - [Console 0]: OperationFailedException: Failed 3 times in the row.
2023-01-01 12:10:21.605578 - [Program]: Program stopped with an exception!
2023-01-01 12:10:21.605701 - [Program]: EventNotification(Program Error (Fatal)): Sending notification.
2023-01-01 12:10:21.605784 - [Program]: Scheduling Webhook Message... (queue = 2)
2023-01-01 12:10:21.605806 - [Program]: Saving historical stats...
2023-01-01 12:10:21.606096 - [Program]: Stats successfully saved!
2023-01-01 12:10:21.606110 - [Program]: Program State: STOPPED
2023-01-01 12:10:21.607549 - [DiscordWebhookSender]: Sending Webhook Message...
2023-01-01 12:10:22.408758 - [DiscordWebhookSender]: Sending Webhook Message...
2023-01-01 12:15:20.482061 - [Console 0]: Sending: controller_state() - seqnum = 5893, button = 4096( BUTTON_HOME ), dpad = 8, LJ = (128,128), RJ = (128,128), ticks = 255
2023-01-01 12:15:20.558953 - [Console 0]: Sending: PABB_MSG_REQUEST_STOP - seqnum = 5894
2023-01-01 12:16:23.270730 - [Console 0]: Sending: PABB_MSG_REQUEST_STOP - seqnum = 5958
2023-01-01 12:20:43.505605 - [Console 0]: Sending: PABB_MSG_REQUEST_STOP - seqnum = 6218
2023-01-01 12:21:06.922739 - [Console 0]: Sending: PABB_MSG_REQUEST_STOP - seqnum = 6242
2023-01-01 12:21:21.587978 - [Console 0]: Sending: PABB_MSG_REQUEST_STOP - seqnum = 6258

**Comment by karasuhebi** [comment] 2023-01-01 17:30
![image](https://user-images.githubusercontent.com/6857825/210179701-239b6b6c-95bc-417d-bb10-72400952f156.png)

**Comment by karasuhebi** [comment] 2023-01-01 21:23
I now realize there's a chance that the current box was set to the right box, not the middle box which I would assume would've caused the issue.

Is there any way to make it so that when the program meets the stop criterion, it makes the current box the middle box again so the user doesn't have to do it themselves when they go to start the program again?

**Comment by Gin890** [comment] 2023-09-06 04:59
Sorry for the very late reply to this issue. We mostly check issues raised in our Discord server.
This is not a bug, but a small convenience feature request: change the current box to the middle box. I personally don't have the need for this, because the three boxes used for egg hatching are distinct enough. It will also be a bit unintuitive if the program always stops at the middle box, so the users do not know what the final act of the program is.

I will close the issue as it's too trivial to me. But thank you for contacting us and providing your suggesion. If you have any other feedback, feel free to submit them on Github or in our Discord server!

**Closed by Gin890** 2023-09-06 04:59 UTC
Labels: bug, PokemonSV
