### ISSUE TITLE
[REQ] - Sword/shield Max Lair standard

### ISSUE THREAD

**Issue by GHOSTASSASSINno1** [PokemonAutomation/ComputerControl#175] opened 2024-01-19 17:01 UTC
**Game**
- [x] Sword/Shield
- [ ] Brilliant Diamond/Shining Pearl
- [ ] Legend Arceus
- [ ] Nintendo Switch Features

When live hosting Max lairs it posts a screenshot of the pokemon its live hosting but now its half blocked by the code screen

![image](https://github.com/PokemonAutomation/ComputerControl/assets/157146626/122d80b5-8347-4a2d-b18c-ce0efc7915a0)
thats how the old screenshots looked like.
![image](https://github.com/PokemonAutomation/ComputerControl/assets/157146626/0e0c8515-c4f4-416e-b444-c828cd628b56)
This is how it looks like now.

I hope you are able to fix this and i understand this is obviously going to be lowest priority cus its not super important.
but i wanted to point it out thank you for your awesome work.

**Comment by Mysticial** [comment] 2024-01-19 23:13
Nothing changed. The program simply messed up the code entry (which happens occasionally). It should automatically time out and reset for the next raid.

**Comment by GHOSTASSASSINno1** [comment] 2024-01-20 04:06
It doesnt its perminent every raid picture is like that hence why i reported it i thought it was a 1 time thing aswell but it does it everytime and it never used 2 do that.

Kind regards,

Don

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by GHOSTASSASSINno1** [comment] 2024-01-20 04:23
And the raid also doesnt mess up the code it continues like normal it just makes the screenshot in the code enter screen instead of in the raid screen

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Mysticial** [comment] 2024-01-20 04:29
Can you give me an example of a code that it fails to enter?

**Comment by GHOSTASSASSINno1** [comment] 2024-01-20 05:33
It never fails to enter the code actually it just seems the screenshot timing is in the code enterscreen and before it was not it started doing it after i updated to the newest version
Sirry my first message got declined for reaching size limit

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Mysticial** [comment] 2024-01-20 06:35
Ok, I managed to reproduce this. You needed to host online with exactly one Switch and have codes enabled.

Looks like this might be a really old bug. Like more than a year old. I'll push a fix, but you'll need to wait for the next release.

**Comment by GHOSTASSASSINno1** [comment] 2024-01-20 07:35
Thanks it didnt seem to be like that at first before updating it was working fine i also have another hoster same thing made screenshots normally after updating to the newest it made pictures of the code screen thank you for looking into this i really appreciatie it love the work all the people working on this <3

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Mysticial** [comment] 2024-12-09 07:37
Closing this since there's been a new release since this was filed. Feel free to reopen if you see it again.

**Closed by Mysticial** 2024-12-09 07:37 UTC
Labels: bug, P4 - Low Priority, PokemonSwSh
